### ISSUE TITLE
Potential attack vector

### ISSUE THREAD

**Issue by missinglink** [williammoran/expiringlink#1]
Hi William, I saw your post on Reddit.

I wanted to mention that encoding the 'rounds' opens up a potential attack vector.

A melicious user could encode a poisoned hash composed of a valid `age` with `math.MaxInt64` for the `rounds` and anything for the `hash`.

Spamming this poisoned hash to the validation server would likely result in a DOS situation.

I'd suggest that you just select a constant value for `rounds` (why not just 1?) so that the decoding step has a fixed cost.

**Comment by williammoran** [comment]
This is a great catch, thanks for reporting it!
Hardcoding the rounds it generally considered bad security practice, as is setting it to 1. A single round isn't considered computationally expensive enough to be secure. And generally speaking the # of rounds needs to be increased as CPU power increases.
However, I think the addition of a MaxRounds parameter can be used to check and prevent the DoS you're describing while still allowing each end user to select their own security vs. CPU usage tradeoff.

**Comment by missinglink** [comment]
Can you explain a little more about how you determine *which* account the hash corresponds to? it's not encoded within the hash itself.

ie. Can I use a valid hash to reset *only* my own email address or can I potentially use it to reset the email address of another user?

**Comment by williammoran** [comment]
The library doesn't have anything for identifying what account the link should be associated with. I don't think it's possible to do that, since each implementation might need something different (i.e. might be a numeric ID or a UUID or a string).
At this point, I'm considering that part of the process to be out of scope for this library, but my thought is that the URL will probably have multiple parts to facilitate.

**Comment by missinglink** [comment]
The reason I ask is that it seems that this information will need to be persisted somewhere, say.. redis or memory or postgres or whatever.

From the readme I understand the problem statement as:

> Theoretically, such a system could be DoSed by generating password resets as fast as possible and overwhelming whatever system is keeping track of the expirations

The traditional approach would be to generate a pseudo-random hash and store it in the db next to the user id, potentially adding a third column with the expiry.

In the case where the user requests multiple password resets (as above) the cost is a single db lookup to check if a hash exists, and if it doesn't, the cost of generating the hash and saving it.

From what I can see this solution suffers the same potential issues from your problem statement, it still requires a db lookup to validate the user but the cost of generating the hash with multiple iterations and the date math make it more costly than the naive implementation?

[edit] in particular the validation step of the naive solution is a simple `==` comparison whereas this solution requires using the same amount of CPU as was used to generate the hash originally.

**Comment by williammoran** [comment]
The problem with your description of the naive solution is that if the hash is close to expiring and the user re-requests it, it might expire before they can use it, and the system will only extend the expiration date if a new hash is generated because the existing one has expired.
As a result, the systems that I've seen generate a new hash with every request, thus a malicious user could fill up the storage with hashes that they're never going to use faster than they will expire.
The description you make of the "naive" system is one of the ways to avoid the attack. But, as noted, it has the downside that there's a window where a user could be issued a reset link that they'll not be able to use before it expires. In practice, the window where this problem could occur probably isn't an issue for most systems. And that's why I'm considering this approach theoretical and experimental.

**Comment by missinglink** [comment]
> As a result, the systems that I've seen generate a new hash with every request

Agh yeah, this is not ideal, a system need only 'extend' the expiry within a threshold of expiration rather than on every request, this oversight is the main cause of the problem you mention in the readme.

Anyway, I'm still not clear on how you would tie this hash to a specific user, saving the computed hash to a database is much the same as the naive approach, if you would like to avoid any DB lookup (such as the 'signed request' feature of AWS S3) then additional information would need to be encoded to facilitate.

**Comment by williammoran** [comment]
I'll update the docs with suggestions on how to use it. I do not expect there to be any need to store the hashes anywhere.

**Comment by missinglink** [comment]
> I'll update the docs with suggestions on how to use it.

Cool, yeah I'm mostly interested in a guarantee that I can't steal *your* account by doing a password reset using the hash generated for *my* account with your email address.

I'm off to bed, all the best.

**Comment by jtorvald** [comment]
Agree with @missinglink here. If it's just a expiring the hash itself then what does it "sign"?

You could use the same hash in combination with another account unless you use for example the creation date time from the user's account as the Epoch. And that's what I think @williammoran intents to do? 

In that case you still do a user lookup which goes into the database and we're back at square one... Or am I missing something here?

I would say you take all the query string parameters including an expiration timestamp. Hash them all together with some secret and you verify them first before you do database work. If the URL is valid then you take the token from the URL and check it for the user that requests the reset.

**Comment by williammoran** [comment]
@jtorvald Yeah, I explained things poorly. I'll try to get the README updated with a better explanation once I have this other issue sorted out.

**Comment by williammoran** [comment]
Closing as an issue. Added protection against the stated attack.
